### ISSUE TITLE
Test compile on osx -errors

### ISSUE THREAD

**Issue by fricy** [splintermind/Dwarf-Therapist#208]
I tried to run a test compile to see if there are any errors:

../../Dwarf-Therapist/inc/dfinstanceosx.h:54:14: warning: 
      'DFInstanceOSX::alloc_chunk' hides overloaded virtual function
      [-Woverloaded-virtual]
    VIRTADDR alloc_chunk(mach_vm_size_t size);
             ^
../../Dwarf-Therapist/inc/dfinstancenix.h:20:22: note: hidden overloaded virtual
      function 'DFInstanceNix::alloc_chunk' declared here
    virtual VIRTADDR alloc_chunk(USIZE size) = 0;
                     ^
../../Dwarf-Therapist/src/dfinstanceosx.mm:64:7: error: type 'DFInstance' is not
      a direct or virtual base of 'DFInstanceOSX'
    : DFInstance(parent)
      ^~~~~~~~~~
../../Dwarf-Therapist/src/dfinstanceosx.mm:166:5: error: use of undeclared
      identifier 'map_virtual_memory'
    map_virtual_memory();

Plus of course #199.

**Comment by fricy** [comment]
Thx, test compile with qt4.8 succesfull. The double icon/process issue in 199 is still around. 
Did I miss something, or did checksum calculations change? DT wanted a new one for 40.13. Should I go and fix all the .ini-s for 28.0?

**Comment by Hello71** [comment]
uh, they should be the same. try both DT versions with both qt versions.

**Comment by fricy** [comment]
Nope, needs new checksum both with 4.8 and 5.3.

**Comment by Hello71** [comment]
what about 27.0 with both?

**Comment by fricy** [comment]
v27 (both 4.8 and 5.3) compiled from cb17b2b generates 0xef35fbe9 for 40.13. Test compile from 68e66dd generates 0xcf35dbe9.

**Comment by Hello71** [comment]
hm. since I'm lazy, mind running md5sum on the DF executables?

**Comment by lethosor** [comment]
```
0.40.12 = 701549c08ec11b4c31df92ee8a8013ff
0.40.13 = cf35dbe91cf4f9abc7637a4a8b03b54b
0.40.14 = 12b458920f49376cbaced0549a092f2e
```

**Comment by Hello71** [comment]
so the old one was wrong then. great.

if changing all the hashes is an option then I wonder if we should move to sha1 and use the whole  hash instead of computing it all just to throw away three-quarters.
